### ISSUE TITLE
teenie bug

### ISSUE THREAD

**Issue by cincinnatus0** [jameshnsears/QuoteUnquote#1]
![xyz](https://user-images.githubusercontent.com/33743101/116033446-f00e5e00-a650-11eb-9f47-6d2801e57ebd.jpeg)
There is this bug where even after disabling every "toolbar" item i.e. share, previous, next, random etc… It takes up a lot of dead space (as you can see in the … It would be nice if there was more flexibility on the resizing)

p.s I am not sure if this is a limitation/fault of my launcher, android widgets or your awesome app.

Help is appreciated, thank you!

**Comment by jameshnsears** [comment]
Hi - thank you for the feedback, and raising this issue.

It's not your launcher, it's how the widget "layout" works at the moment.

I'll take a look and see if I can hide this "extra space" when all "toolbar" buttons are disabled.

I'm in the processes of creating another release, any such fix to this issue might come after the impending release.

**Comment by jameshnsears** [comment]
Fixed - the "dead space" will now be occupied by the quotation.

Code change will be included in the next release.

Again, thanks for raising the issue :-)

**Comment by cincinnatus0** [comment]
Hey - thank you for being so proactive in the development.

The latest update also did not fix the very specific issue that I have it yet is taking up extra dead space I am guessing it has something to do with the block size of the widget i.e. 3 x 2, so I am guessing providing more options like 2 x 2, 3 x 3 etc might end up fixing it... It's not as big of a dealbreaker as I make it sound please look into it whenever you are free.

But currently, after the new update the color "black" is missing for some reason. (unable to get that clean transparent look like I had from my previous screenshot) 

Once again Thank you :D 
Stay Home, Stay Safe

![signal-2021-04-27-083920](https://user-images.githubusercontent.com/33743101/116212295-37b9e600-a734-11eb-9d3f-6247e9dc8d3b.jpeg)

**Comment by jameshnsears** [comment]
I'll add Black to the backgrounds; together with bringing back font colour selection; and, the "dead space" fix, in the next release: 2.2.0.

There's **maybe** no need for anything other than 3x2 - as the widget is resizeable (at least beyond 3 x 2). However, I'll add 2x2 & 3x3 on the Trello board I use to track things ideas / requests.
